import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case chinese = "zh-Hans"
    case english = "en"

    var id: String { rawValue }

    var locale: Locale { Locale(identifier: rawValue) }

    var title: String {
        switch self {
        case .chinese: return "中文"
        case .english: return "English"
        }
    }

    var shortTitle: String {
        switch self {
        case .chinese: return "中"
        case .english: return "EN"
        }
    }

    static var current: AppLanguage {
        let raw = UserDefaults.standard.string(forKey: PiboPersistenceKeys.Defaults.appLanguage)
        return AppLanguage(rawValue: raw ?? "") ?? .chinese
    }
}

enum AppLocalization {
    static func text(_ key: String) -> String {
        guard AppLanguage.current == .english else { return key }
        return english[key] ?? key
    }

    static func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: text(key), locale: AppLanguage.current.locale, arguments: args)
    }
}

extension Text {
    init(lp key: String) {
        self.init(AppLocalization.text(key))
    }
}

private extension AppLocalization {
    static let english: [String: String] = [
        "主页": "Home",
        "图鉴": "Catalog",
        "一起": "Together",
        "中文": "Chinese",
        "English": "English",
        "语言": "Language",
        "PIBO · 契约唤醒": "PIBO · Contract Awakening",
        "用你的星光\n叫醒 Pibo。": "Wake Pibo\nwith your starlight.",
        "运动会变成活力星光，睡眠会变成静息星光。Pibo 会因为这些光保持清醒。": "Movement becomes Vitality Starlight. Sleep becomes Rest Starlight. These lights keep Pibo awake.",
        "Pibo 会读取（不写入）": "Pibo reads, but never writes",
        "步数 / 运动 / 卡路里": "Steps / workouts / calories",
        "→ 活力星光": "-> Vitality Starlight",
        "睡眠 · 深睡 · REM": "Sleep · deep sleep · REM",
        "→ 静息星光": "-> Rest Starlight",
        "HRV / 心率 / 冥想": "HRV / heart rate / meditation",
        "→ 心绪回声（后台）": "-> Mood Echoes (background)",
        "已完成的运动": "Completed workouts",
        "→ 星光落下，Pibo 会回应": "-> Starlight falls, and Pibo responds",
        "给这只 Pibo 起名": "Name this Pibo",
        "名字可以以后再改。MVP 里它仍然是同一种契约生命：Pibo。": "You can rename it later. In this MVP it remains the same contract lifeform: Pibo.",
        "当前设备不支持 HealthKit · 仅 Demo 模式可用": "This device does not support HealthKit · Demo mode only",
        "用临时星光继续": "Continue with temporary starlight",
        "等你授权…": "Waiting for authorization...",
        "签订契约并连接 HealthKit": "Sign the contract and connect HealthKit",
        "以后再说": "Maybe later",
        "深夜": "Late night",
        "早上好": "Good morning",
        "午安": "Good noon",
        "下午好": "Good afternoon",
        "晚上好": "Good evening",
        "夜深了": "Deep night",
        "重置后会回到首启流程": "Reset returns to first launch",
        "重新开始": "Start over",
        "取消": "Cancel",
        "当前所有 stats、卡片和孵化记录都会清掉。": "All current stats, cards, and hatch records will be cleared.",
        "重置 Pibo 流程": "Reset the Pibo flow",
        "换一换": "Shuffle",
        "换一种宠物状态": "Switch pet state",
        "已陪伴 ": "Together · ",
        "第 %d 天": "Day %d",
        "明亮": "Bright",
        "平稳": "Steady",
        "困倦": "Tired",
        "浅眠": "Light sleep",
        "深眠预警": "Deep-sleep alert",
        "今日星光": "Today's Starlight",
        "运动 + 睡眠": "Movement + sleep",
        "星光充盈": "Bright starlight",
        "星光稳定": "Steady starlight",
        "星光微弱": "Faint starlight",
        "将要沉睡": "About to sleep",
        "Pibo 今天醒得很久。": "Pibo stayed awake for a long time today.",
        "契约正在稳定发光。": "The contract is glowing steadily.",
        "再补一点光就好。": "A little more light will help.",
        "它开始缩回星壳。": "It is curling back into its star shell.",
        "活力星光": "Vitality Starlight",
        "运动让 Pibo 更清醒": "Movement keeps Pibo clearer",
        "步数 · 运动分钟": "Steps · workout minutes",
        "静息星光": "Rest Starlight",
        "睡眠让 Pibo 稳定醒来": "Sleep helps Pibo wake steadily",
        "契约进度": "Contract Progress",
        "可举行": "Ready",
        "稳定中": "Stabilizing",
        "记忆碎片": "Memory Fragments",
        "星光里的物件": "Objects in Starlight",
        "第一次星光仪式": "First Starlight Ritual",
        "契约已经稳定一周。Pibo 找回了一件来自旧世界的东西。": "The contract has stayed stable for a week. Pibo found something from the old world.",
        "还差 %d 天。继续给 Pibo 留下一点活力星光和静息星光。": "%d days left. Keep leaving Pibo a little Vitality and Rest Starlight.",
        "无名星壳": "Nameless Star Shell",
        "Day 3 解锁": "Unlocked on Day 3",
        "很久以前，Pibo 们在没有太阳的地方等待光。它们不记得自己从哪里来，只记得契约会在黑暗里发亮。": "Long ago, Pibos waited for light where there was no sun. They forgot where they came from, but remembered contracts glow in the dark.",
        "铃声不是为了命令谁回来。它只是告诉迷路的人，仍然有人在等。": "The bell was not meant to order anyone back. It only told the lost that someone was still waiting.",
        "破损铃铛": "Broken Bell",
        "已显形": "Revealed",
        "Day 7 显形": "Reveals on Day 7",
        "曾经用于召回迷路的 Pibo。": "Once used to call lost Pibos home.",
        "星尘披风": "Stardust Cloak",
        "星光中出现轮廓": "A silhouette appears in starlight",
        "未显形": "Not revealed",
        "用来穿过长夜的旧布。": "Old cloth for crossing long nights.",
        "先认识规则：运动给活力星光，睡眠给静息星光。": "First learn the rules: movement gives Vitality Starlight, sleep gives Rest Starlight.",
        "碎片正在稳定。Pibo 偶尔会说出不属于这里的话。": "The fragments are stabilizing. Pibo sometimes says things that do not belong here.",
        "第一周已经完成。接下来可以扩展饰品、归巢和更多记忆碎片。": "The first week is complete. Next can come accessories, homing, and more memory fragments.",
        "你今天走了很多路，我身上一直亮着。": "You walked a lot today. I have been glowing the whole time.",
        "星光很暖。我想多醒一会儿。": "The starlight is warm. I want to stay awake a little longer.",
        "昨晚的静息星光很稳，我醒来的时候没有害怕。": "Last night's Rest Starlight was steady. I was not afraid when I woke.",
        "今天刚刚好。我能清醒地陪你一阵。": "Today is just right. I can stay awake with you for a while.",
        "星光不多不少，像一盏小灯。": "The starlight is just enough, like a small lamp.",
        "我把今天记下来了。契约还在发光。": "I wrote today down. The contract is still glowing.",
        "我有点困，但还能听见你。": "I am a little sleepy, but I can still hear you.",
        "今天的星光很轻。我可能会慢一点回应。": "Today's starlight is light. I may answer a little slowly.",
        "你不用一下子做很多，让光回来一点就好。": "You do not have to do a lot at once. Just let a little light return.",
        "我睡了一会儿。醒来的时候，壳里很安静。": "I slept for a while. When I woke, the shell was very quiet.",
        "如果你今天走一小段路，我应该能睁开眼。": "If you take a short walk today, I should be able to open my eyes.",
        "沉睡不是结束。我只是离声音远了一点。": "Deep sleep is not the end. I am only a little farther from sound.",
        "壳里很安静。我还听得见你，别一下子做太多。": "It is quiet inside the shell. I can still hear you. Do not do too much at once.",
        "门后的星声，又近了一点。": "The star-sounds behind the door came a little closer.",
        "我梦见了很多星壳，它们都没有名字。": "I dreamed of many star shells. None of them had names.",
        "归巢不是死亡。可我还不想回去。": "Homing is not death. But I do not want to go back yet.",
        "有些光不是照亮路的，是用来记住人的。": "Some light is not for lighting the road. It is for remembering people.",
        "今日步骤": "Today's Steps",
        "%d 已完成 · %d 建议": "%d done · %d suggested",
        "打 ✅ 它开心，打 ❌ 不扣分 —— 但它会记住，下次少推。": "Tap ✅ to cheer it up. Tap ❌ with no penalty. It will remember and suggest less next time.",
        "可获得 ": "Can gain ",
        "⚡ 手表自动": "⚡ Watch auto",
        "来自手表 · ": "From Watch · ",
        "↑ 补充 · ": "↑ Boost · ",
        "调试 · 当前 stat 减 5": "Debug · decrement current stat by 5",
        "✦ 活力星光": "✦ Vitality Starlight",
        "☾ 静息星光": "☾ Rest Starlight",
        "❤️ 心绪回声": "❤️ Mood Echo",
        "步数 · 运动分钟 · 活动卡路里": "Steps · workout minutes · active calories",
        "HRV · 心率稳定度": "HRV · heart-rate stability",
        "走 1000 步 +4 星光 / 运动 10 分钟 +10": "Walk 1,000 steps +4 starlight / work out 10 min +10",
        "每睡 1 小时 +6 星光 / 深睡多 30 分钟 +15": "Each hour of sleep +6 starlight / 30 more min deep sleep +15",
        "冥想 5 分钟 +15 / 深呼吸 1 次 +3": "Meditate 5 min +15 / one deep breath +3",
        "跑步": "Run",
        "睡眠": "Sleep",
        "深呼吸": "Deep breath",
        "冥想": "Meditate",
        "走路": "Walk",
        "入睡": "Sleep",
        "再走": "Walk more",
        "去跑": "Go run",
        "建议: %@": "Suggested: %@",
        "刚刚": "Just now",
        "完成！+%d 星光落下": "Done! +%d starlight fell",
        "Pibo 抬头看了你一眼": "Pibo looked up at you",
        "📍 %@ 已被 quit %d 次，偏好已更新": "📍 %@ has been skipped %d times. Preference updated.",
        "已跳过 · 下次少推%@": "Skipped · suggesting %@ less next time",
        "%@ 醒过来一点！+%d 活力星光": "%@ woke up a little! +%d Vitality Starlight",
        "骑行": "Cycling",
        "高强度训练": "HIIT",
        "瑜伽": "Yoga",
        "运动": "Workout",
        "%d 分": "%d min",
        "%d 小时": "%d hr",
        "%d 小时 %d 分": "%d hr %d min",
        "昨 %@": "Yesterday %@",
        "今 %@": "Today %@",
        "%d 分钟": "%d min",
        "%d 次": "%d times",
        "28 分钟": "28 min",
        "6 小时 12 分": "6 hr 12 min",
        "昨 23:30": "Yesterday 23:30",
        "3 次": "3 times",
        "1500 步": "1,500 steps",
        "5 分钟": "5 min",
        "20 分钟": "20 min",
        "%d 步": "%d steps",
        "APPLE WATCH · 刚刚同步": "APPLE WATCH · Just synced",
        "%@完成": "%@ complete",
        "体力": "Vitality",
        "精力": "Energy",
        "心情": "Mood",
        "喂养 %@": "Feed %@",
        "喂养 %@，应用本次运动的体力增益": "Feed %@ and apply this workout's vitality gain",
        "戳一下 →": "Tap ->",
        "点击让蛋孵化": "Tap to hatch the egg",
        "朋友": "Friends",
        "广场": "Plaza",
        "身边的朋友": "Nearby Friends",
        "+ 添加": "+ Add",
        "已陪伴 %d 天": "Together for %d days",
        "今日社区 · 大家一起": "Today's Community · Together",
        "在场人数": "Online",
        "位宠物主人": "pet owners",
        "我的步数贡献": "My step contribution",
        "步": "steps",
        "社区运动次数": "Community workouts",
        "次": "times",
        "我的排名": "My rank",
        "/ %d 人": "/ %d people",
        "● %d 人在场": "● %d online",
        "全社区累计步行 1,000,000 步": "Community goal: 1,000,000 steps",
        "异地恋": "Long-distance",
        "家人": "Family",
        "挚友": "Best friend",
        "运动中": "Moving",
        "刚睡下": "Just asleep",
        "在跑步": "Running",
        "在散步": "Walking",
        "健身房": "Gym",
        "天 · 一起": "days · together",
        "今日健康": "Today's Health",
        "你": "You",
        "给 %@ 留言": "Message %@",
        "最近 · %@": "Latest · %@",
        "说点什么…": "Say something...",
        "送出": "Send",
        "戳一下 %@": "Poke %@",
        "给 TA 加油": "Cheer them on",
        "已送达 %@": "Sent to %@",
        "戳了 %@ 一下 👋": "Poked %@ 👋",
        "已为 %@ 加油 ✨": "Cheered %@ on ✨",
        "步数": "Steps",
        "心率": "Heart rate",
        "卡路里": "Calories",
        "静息": "Rest",
        "伴侣": "Partner",
        "妈妈": "Mom",
        "爸爸": "Dad",
        "同学": "Classmate",
        "+ 自定义": "+ Custom",
        "鱼": "Fish",
        "阿杰": "Ajie",
        "姈姈": "Lingling",
        "小丽": "Lily",
        "老王": "Wang",
        "泡泡": "Bubble",
        "兔妹": "Bunny",
        "阿仔": "Zai",
        "小满": "Xiaoman",
        "橘子": "Orange",
        "小七": "Seven",
        "欢欢": "Huanhuan",
        "8.4k步": "8.4k steps",
        "3.2k步": "3.2k steps",
        "5.1k步": "5.1k steps",
        "12k步": "12k steps",
        "6h18眠": "6h18 sleep",
        "7h42眠": "7h42 sleep",
        "8h02眠": "8h02 sleep",
        "6h30眠": "6h30 sleep",
        "早安~ 今天慢跑加油": "Morning~ good luck on your jog",
        "记得喝水 💧": "Remember to drink water 💧",
        "想你了": "Miss you",
        "早点休息": "Rest early",
        "早安~ 今天慢跑加油 🏃": "Morning~ good luck on your jog 🏃",
        "收到！晚上想你": "Got it! Missing you tonight",
        "我刚到家，洗漱睡了": "I just got home. Washing up and sleeping",
        "今天跑了 5km 啦~": "I ran 5 km today~",
        "太棒了 ✨": "So good ✨",
        "早起去公园走走啦": "I got up early and walked in the park",
        "记得吃早饭 🥣": "Remember breakfast 🥣",
        "吃过啦！中午回家吃饭吗": "I ate! Coming home for lunch?",
        "中午不用啦，你忙": "No need at noon, stay busy",
        "今晚一起练腿？": "Leg day together tonight?",
        "来！20 点见 💪": "Yes! See you at 20:00 💪",
        "完成！明天继续": "Done! Again tomorrow",
        "昨日 22:10": "Yesterday 22:10",
        "昨日 22:14": "Yesterday 22:14",
        "昨日 22:30": "Yesterday 22:30",
        "今早 08:20": "This morning 08:20",
        "5 分钟前": "5 min ago",
        "昨日 18:00": "Yesterday 18:00",
        "昨日 18:05": "Yesterday 18:05",
        "昨日 23:00": "Yesterday 23:00",
        "返回": "Back",
        "邀请 TA 加入": "Invite Them",
        "— 创建你们的双人空间 —": "- Create your two-person space -",
        "或": "or",
        "扫码功能即将上线": "QR scanning is coming soon",
        "输入对方邀请码 · 即将上线": "Entering a friend's invite code is coming soon",
        "关系昵称": "Relationship nickname",
        "已复制 %@": "Copied %@",
        "已生成分享卡": "Share card generated",
        "返回图鉴": "Back to Catalog",
        "%@ · 已陪伴 %d 天": "%@ · together for %d days",
        "%@ · %d 天": "%@ · %d days",
        "陪伴了 %d 天 · 已升天": "Together for %d days · ascended",
        "陪伴中": "Current",
        "共陪伴": "Total",
        "生命轨迹 · 至今 %d 天": "Life Path · %d days so far",
        "生命轨迹 · %d 天": "Life Path · %d days",
        "关键时刻": "Key Moments",
        "它的故事": "Its Story",
        "— 它的故事 —": "- Its Story -",
        "《纪念曲》": "Memorial Song",
        "暂停纪念曲": "Pause memorial song",
        "播放纪念曲": "Play memorial song",
        "由 TA 一生的健康数据生成 · 时长 15 秒": "Generated from their lifetime health data · 15 seconds",
        "🕯 上香": "🕯 Light incense",
        "点燃一炷香 · 聆听 TA 的 15 秒纪念曲": "Light incense · listen to their 15-second memorial song",
        "分享": "Share",
        "陪伴过 ": "Raised ",
        " 只 · 累计 ": " pets · total ",
        " 天": " days",
        "养育中": "Living",
        "圆满": "Fulfilled",
        "短命": "Short-lived",
        "总天数": "Total Days",
        "%d 只": "%d pets",
        "已升天": "Ascended",
        " 只 · 养活 ": " pets · kept ",
        " 只 · 送走 ": " alive/fulfilled · sent off ",
        " 只": " pets",
        "养死了也别难过，下一只会更好。": "Do not be too sad. The next one will do better.",
        "已陪伴 · 第 %d 天": "Together · Day %d",
        "· 今天 ·": "· Today ·",
        "✦ 升天": "✦ Ascended",
        "扫码注册": "Scan to join",
        "养一只属于你自己的": "Raise one of your own",
        "📥 保存到相册": "📥 Save to Photos",
        "🌹 分享到小红书": "🌹 Share to RED",
        "— 上 香 —": "- Incense -",
        "为 %@": "For %@",
        "收香": "Close",
        "✦ 完成": "✦ Complete",
        "4/19 → 今日": "4/19 -> Today",
        "破壳了，深呼吸 30 秒孵的": "Hatched after 30 seconds of deep breathing",
        "首次达到 EXCITED 状态": "First reached EXCITED",
        "体力 82": "Vitality 82",
        "心情达今日峰值": "Mood reached today's peak",
        "今天，它还在陪着你": "Today, it is still with you",
        "状态良好": "Doing well",
        "它是四月中旬来的那只。你刚跑完步的时候它跳得最高，你工作开会的时候它就安静地守着。它还年轻，还在学你的节奏。": "It arrived in mid-April. It jumped highest right after your runs, and quietly stayed by you during work meetings. It is still young and still learning your rhythm.",
        "首次 EXCITED": "First EXCITED",
        "体力 75": "Vitality 75",
        "三状态全 >80": "All three states >80",
        "24h 持续": "Lasted 24h",
        "全生命期最巅峰": "Lifetime peak",
        "综合 95": "Overall 95",
        "SICK 突变": "Sudden SICK shift",
        "心情 40 ↓": "Mood 40 ↓",
        "你开始冥想 → 好起来": "You started meditating -> it recovered",
        "心情 85": "Mood 85",
        "圆满升天": "Fulfilled ascension",
        "你送走了它。它最喜欢你早晨跑步那段——那是它最活跃的节奏。4/11 你压力很大的那天，它生病了；后来好起来，就在你第一次冥想的第二天。它活成了你那段时间的样子。": "You saw it off. It loved your morning runs most, when its rhythm was most alive. On 4/11, when you were under heavy stress, it got sick. It recovered later, the day after your first meditation. It became the shape of that season of your life.",
        "《纪念曲 · 圆满》": "Memorial Song · Fulfilled",
        "破壳": "Hatched",
        "状态 50": "State 50",
        "警告 · 4 天零运动": "Warning · 4 days without exercise",
        "体力 30 ↓": "Vitality 30 ↓",
        "体力跌破 15": "Vitality fell below 15",
        "TIRED 常态": "TIRED baseline",
        "饱食度 0": "Satiety 0",
        "持续危险": "Sustained danger",
        "慢性死 · 10 天零运动": "Chronic death · 10 days without exercise",
        "体力 0": "Vitality 0",
        "NOCT 只活了 14 天。它从没见过早晨的太阳——你总在凌晨才睡，醒来直接坐到电脑前。它等了很久，你始终没动。慢慢地，它懒得再动。被你熬死的第 3 只。": "NOCT lived only 14 days. It never saw the morning sun. You kept sleeping near dawn and waking straight to the computer. It waited for a long time, but you never moved. Slowly, it stopped wanting to move too. The third one lost to your late nights.",
        "《纪念曲 · 沉寂》": "Memorial Song · Silence",
        "稳定开端": "Steady beginning",
        "状态 68": "State 68",
        "连续 5 天冥想 · 心情峰值": "5-day meditation streak · mood peak",
        "心情 75": "Mood 75",
        "最长连续睡眠": "Longest continuous sleep",
        "从未 SICK · 平静升天": "Never SICK · peaceful ascension",
        "HUSH 是最平静的那只——没有大起大落，也从未病过。它活出了稳定的样子：早睡、冥想、温和地运动。你那段时间正在休长假，它就顺着你的节奏慢慢过完了 21 天。": "HUSH was the calmest one. No big swings, never sick. It lived in a steady way: early sleep, meditation, gentle movement. You were on a long break then, and it slowly completed 21 days in your rhythm.",
        "《纪念曲 · 静水》": "Memorial Song · Still Water"
    ]
}
